BKProjekt/Controllers/UserListController.cs
using BKProjekt.Areas.Identity.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BKProjekt.Controllers
{
    public class UserListController : Controller
    {
        private readonly BKProjektDbContext _context;
        private readonly UserManager<BKProjektUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        public UserListController(UserManager<BKProjektUser> userManager, BKProjektDbContext context, RoleManager<IdentityRole> roleManager)
        {
            _context = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }
        public async Task<IActionResult> UserList()
        {
            var role = await _roleManager.FindByNameAsync("user");
            if (role == null)
            {
                return View(new List<BKProjektUser>());
            }
            var userRoleIds = await _context.UserRoles
                .Where(ur => ur.RoleId == role.Id)
                .Select(ur => ur.UserId)
                .ToListAsync();
            var users = await _userManager.Users
                .Where(u => userRoleIds.Contains(u.Id))
                .ToListAsync();

            return View(users);
        }

        
        [HttpPost]
        public async Task<IActionResult> BorrowsList(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound();
            }

            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }

            var borrows = await _context.Borrows
                .Include(b => b.Book)
                .Where(b => b.UserId == id)
                .OrderByDescending(b => b.BorrowDate)
                .ToListAsync();

            ViewBag.UserName = user.UserName;
            return View(borrows);
        }
    }
}

BKProjekt/Views/UserList/BorrowsList.cshtml
@using Microsoft.AspNetCore.Identity
@model IEnumerable<BKProjekt.Models.Borrow>

<h3 class="fw-semibold">Wypożyczalnia @ViewBag.UserName</h3>

<table class="table table-secondary table-striped-columns table-hover rounded-3">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BorrowDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ReturnDate)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.Title
                </td>
                <td>
                    @item.BorrowDate
                </td>
                <td>
                    @item.ReturnDate
                </td>
            </tr>
        }
    </tbody>
</table>

BKProjekt/Views/UserList/UserList.cshtml
@using Microsoft.AspNetCore.Identity
@model IEnumerable<IdentityUser>

<h3 class="fw-semibold">Lista użytkowników</h3>

<table class="table table-secondary table-striped-columns table-hover rounded-3">
    <thead>
        <tr>
            <th>
                Użytkownik
            </th>
            <th>
                Dane
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.UserName
                </td>
                <td>
                    <form asp-action="BorrowsList" asp-controller="UserList" method="post" asp-route-id="@item.Id">
                        <button type="submit" class="btn btn-success">Lista wypożyczonych książek</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>